language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-docpad' ]; then cd .. && eval "mv $currentfolder generator-docpad" && cd generator-docpad; fi
notifications:
  email: false
